<a href="https://colab.research.google.com/github/s1063724/2024python_analysis/blob/main/example/0105database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# json
# csv(Excel)
# 資料庫:Oracle, SQL Server, DB2, MySql, SQLite
# 資料庫本體，table

import sqlite3

# 連線並建立school.db
conn = sqlite3.connect('school.db')
# dataset資料集: 欄位; 列
# 聯想excel資料表裡的一筆資料
cur = conn.cursor()
# 資料庫的語言:SQL
# 內嵌sql語法;對資料庫建立一個名稱為stu的資料表(table)
# stu: stuid INTEGER PRIMARY KEY, name VARCHAR(20), phone VARCHAR(10)
cur.execute('CREATE TABLE stu(stuid INTEGER PRIMARY KEY,name VARCHAR(20), phone VARCHAR(10))')


In [ ]:
cur.execute('DROP TABLE stu')

In [ ]:
cur.execute("INSERT INTO stu VALUES(113001, '王先生', '0905662336')")
cur.execute("INSERT INTO stu VALUES(113002, '李先生', '0909662336')")
cur.execute("INSERT INTO stu VALUES(113003, '張生', '0909523336')")
cur.execute("INSERT INTO stu VALUES(113004, '琛未依', '0909475836')")
cur.execute("INSERT INTO stu VALUES(113005, '李ㄟ屋', '0909574125')")

In [ ]:
cur.execute('SELECT * FROM stu')
# 取得資料
rows = cur.fetchall()
print(type(rows))
print(rows)
print(type(rows[1]))
print(rows[1])

print('-----------------------')
for row in rows:
  print(row[0], row[1], row[2])

# 最後不用記得要關閉，避免佔用資源
# cur.close()

<class 'list'>
[(113001, '王先生', '0905662336'), (113002, '李先生', '0909662336'), (113003, '張生', '0909523336'), (113004, '琛未依', '0909475836'), (113005, '李ㄟ屋', '0909574125')]
<class 'tuple'>
(113002, '李先生', '0909662336')
-----------------------
113001 王先生 0905662336
113002 李先生 0909662336
113003 張生 0909523336
113004 琛未依 0909475836
113005 李ㄟ屋 0909574125


In [ ]:
cur.execute('SELECT * FROM stu')
# 取得一筆
row = cur.fetchone()
print(row[0],row[1])
print('--------------------------------------------')
# 因為前面已經取出1筆資料了，所以在取得只能取得剩下的4筆資料
data = cur.fetchall()
for row in data:
  # 取得list
  # print(row)
  # 取得個別資料
  print(row[0], row[1], row[2])

113001 王先生
--------------------------------------------
113002 李先生 0909662336
113003 張生 0909523336
113004 琛未依 0909475836
113005 李ㄟ屋 0909574125


In [ ]:
# 向量， 矩陣
# 電腦資料處理
# 資料科學(Data Science)
# Numpy -> 向量與矩陣運算;Pandas -> 資料處理;Matplotlib -> 2D繪圖;Seaborn豐富的圖形
# Numpy : ndarry
# 向量(vectory);矩陣(matrix)
# 向量:方向與大小的值:速度、加速度、動力
# 向量:序列的值:[2, 5, -9], 2i+4j+6k

# 矩陣: 2維度的表格(欄、列)

# 陣列
import numpy as np
# 用串列建立ndarray
a = np.array([1, 2, 3, 4, 5])
# 用tuple建立ndarray
b = np.array((1, 2, 3, 4, 5))
print(a)
print(type(a))
print('--------------')
print(b)
print(type(b))


[1 2 3 4 5]
<class 'numpy.ndarray'>
--------------
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 針對每個元素都給予索引值
print(a[0], a[1], a[2], a[3], a[4])
a[0] = 90
print(a)

1 2 3 4 5
[90  2  3  4  5]


In [ ]:
# 二維陣列
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
# c[0,0] = 1, c[0,1] = 2
print('-------------------')
print(c[1,1])

[[1 2 3]
 [4 5 6]]
-------------------
5


In [ ]:
# 指定元素類型
d = np.array([1,2,3,4,5], dtype = float)
print(type(d[0]))
print(d)

<class 'numpy.float64'>
[1. 2. 3. 4. 5.]


In [ ]:
# 指定一個範圍的陣列
e = np.arange(5)
print(e)
# 產生1-5間格2的陣列
f = np.arange(1, 6, 2)
print(f)

[0 1 2 3 4]
[1 3 5]


In [ ]:
g = np.zeros(2)
print(g)

h = np.ones(5)
print(h)
# 產生兩個元素，值都是7
i = np.full(2,7)
print(i)

j_ex = np.array([[1, 5, 6], [5, 8, 9]])
j = np.zeros_like(j_ex)
print(j)

# 產生對角線是1的矩陣
k = np.eye(3)
print(k)
print('--------------------')
l = np.eye(3, k = 1)
print(l)
print('--------------------')
m = np.eye(3, 1)
print(m)

n = np.random.rand(3, 5)
print(n)

[0. 0.]
[1. 1. 1. 1. 1.]
[7 7]
[[0 0 0]
 [0 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
--------------------
[[1.]
 [0.]
 [0.]]
[[0.00428708 0.51467293 0.27003424 0.76057467 0.17597863]
 [0.10164741 0.27549392 0.95639944 0.68442266 0.47087019]
 [0.79403871 0.63346126 0.35947226 0.39764382 0.06047883]]


In [ ]:
a = np.arange(16)
print(a)
print('------------------------')
b = a.reshape((4, 4))
print(b)
print('------------------------')
c = b.reshape(16)
print(c)
print('------------------------')

# d = np.array(range(10), dtype= float)
d = np.array(range(10), float)
print(d)
e = d.reshape((5,2))
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
------------------------
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [ ]:
# numpy -> function()
# 屬性 .attribute
# dtype, size, shape, itemsize, ndim, nbytes

a = np.array([[11, 12, 13, 14, 15],[16, 17, 18, 19, 20], [21, 22, 23, 24, 25],[26, 27, 28, 29, 30]])
print(a.dtype)
print(a.shape)
# 每個元素的byte數
print(a.itemsize)
print(a.ndim)
# 位元
print(a.nbytes)

int64
(4, 5)
8
2
160


In [ ]:
# 走訪陣列元素:迴圈
a = np.array([[11, 12, 13, 14, 15],[16, 17, 18, 19, 20], [21, 22, 23, 24, 25],[26, 27, 28, 29, 30]])
a1 = np.array([1, 2, 3, 4, 5])
for ele in a1:
  print(ele)
  print('----')

# 走訪二維陣列
for ele in a:
  print(ele)
print('-------------------')
for ele in a:
  for item in ele:
    print(str(item)+ " ",end ="")
print()
print('-------------------')
for ele in a:
  for item in ele:
    print(item)



1
----
2
----
3
----
4
----
5
----
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
[26 27 28 29 30]
-------------------
11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 
-------------------
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
