<a href="https://colab.research.google.com/github/s1063724/2024python_analysis/blob/main/example/0108datanumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 陣列、向量
# a =  [a1, a2, a3] 向量
# s = 5 純量scalar
# c = a + s = [a1+s, a2+s, a3+s]
import numpy as np

a= np.array([1,2,3])
print('v='+str(a))
s = 5
print('s='+str(s))
b = a + s
# 向量的加法運算
print('a + s =',str(b))

# 減法運算c = a - s
c = a - s
print('a - s =',str(c))

d = a * s
print('a * s =',str(d))

e = a / s
print('a / s =',str(e))
# 串列相加
f = [4, 5, 6]
g = [1, 2, 3]
h = f + g
print(str(h))
# 向量之間的運算
i = np.array([4, 5, 6])
j = np.array([1, 2, 3])
k = i * j
print(str(k))

v=[1 2 3]
s=5
a + s = [6 7 8]
a - s = [-4 -3 -2]
a * s = [ 5 10 15]
a / s = [0.2 0.4 0.6]
[4, 5, 6, 1, 2, 3]
[ 4 10 18]


In [ ]:
# 向量 點積 運算 -dot product
a = np.array([1,2,3])
print('a='+str(a))
s=np.array([4,5,6])
print('s='+str(s))
c = a.dot(s)
# (1 * 4) + (2 * 5) + (3 * 6)
print('a dot s='+str(c))


a=[1 2 3]
s=[4 5 6]
a dot s=32


In [ ]:
# 向量 與 布林值 遮罩(mask)
a = np.array([14,8,10,11,6,3,18,13,12,9])
print('a = '+str(a))
# 遮照向量
mask = (a % 3 == 0)
print('mask = '+str(mask))
# 用布林值遮罩取出值
b = a[mask]
print('b = '+str(b))

for ele in b:
  print(ele, end=' ')

a = [14  8 10 11  6  3 18 13 12  9]
mask = [False False False False  True  True  True False  True  True]
b = [ 6  3 18 12  9]
6 3 18 12 9 

In [ ]:
# 陣列的函式
# ravel(), flatten() -> 把陣列拉平 -> 一個維度
a = np.array([[1,2,3],[4,5,6]])
# 二維變一維
b = a.ravel()
e = a.flatten()
print(str(b))
print(str(e))
print()
# reshape() -> 改變陣列形狀
c = np.reshape(b, (2, 3))
print(str(c))
print()
d = np.reshape(c, (3, 2))
print(str(d))


[1 2 3 4 5 6]
[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]
