<a href="https://colab.research.google.com/github/s1063724/2024python_analysis/blob/main/example/0122%E6%88%BF%E5%83%B9%E9%A0%90%E6%B8%AC(%E8%A4%87%E8%BF%B4%E6%AD%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#http://lib.stat.cmu.edu/datasets/boston

import numpy as np
import pandas as pd
# sep是區隔符號，s+ : 多個space
# skiprows:跳過前面22行
raw_df = pd.read_csv('boston.csv', sep='\s+', skiprows=22, header=None)
raw_df.head(10)

0      1      2    3      4      5     6       7    8      9     10
0    0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3
1  396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
2    0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8
3  396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
4    0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8
5  392.83000   4.03  34.70  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
6    0.03237   0.00   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7
7  394.63000   2.94  33.40  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN
8    0.06905   0.00   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7
9  396.90000   5.33  36.20  NaN    NaN    NaN   NaN     NaN  NaN    NaN   NaN

In [16]:
# hstack水平堆疊(觀察後發現此資料每14筆為1串資料，但被分成了兩行)
# ::2最前面到最後隔2個抓一個
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
# 前面抓的是:0、2、4、6、8 ....整列資料
# 後面抓的是:1、3、5、7....前兩行的資料
# 目的將兩列資料合併為一列((第14筆為房屋均價，作為目標所以不抓))
target = raw_df.values[1::2, 2]# 第14筆資料(房屋均價)
print(data)
print(data.shape)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]
(506, 14)


In [18]:
# test
a = np.array([[1,2,3,4,5,6,7,8,9],[2,2,3,4,5,6,7,8,9],[3,2,3,4,5,6,7,8,9],[4,2,3,4,5,6,7,8,9],
 [5,2,3,4,5,6,7,8,9],[6,2,3,4,5,6,7,8,9],[7,2,3,4,5,6,7,8,9]])
print(a)
print('-----------')
print(a[::2, :])
print('------------')
print(a[1::2, 2])


[[1 2 3 4 5 6 7 8 9]
 [2 2 3 4 5 6 7 8 9]
 [3 2 3 4 5 6 7 8 9]
 [4 2 3 4 5 6 7 8 9]
 [5 2 3 4 5 6 7 8 9]
 [6 2 3 4 5 6 7 8 9]
 [7 2 3 4 5 6 7 8 9]]
-----------
[[1 2 3 4 5 6 7 8 9]
 [3 2 3 4 5 6 7 8 9]
 [5 2 3 4 5 6 7 8 9]
 [7 2 3 4 5 6 7 8 9]]
------------
[3 3 3]
