<a href="https://colab.research.google.com/github/s1063724/2024python_analysis/blob/main/example/1218datamining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(sum(range(1,101)))

5050


In [ ]:
a = 1 #integer
b = "hello" #string '',"",""""""
a
b

'hello'

In [ ]:
hello = "Hello"
height = 178
say_hi = hello
print(say_hi)

Hello


In [ ]:
weight = 70
weight = weight + 2
bmi =weight/height/height
bmi
print(bmi)

0.0022724403484408536


In [ ]:
# 多重指定敘述
score1 = score2 = score3 = 35
print(score1, score2, score3)

35 35 35


In [ ]:
# 同時指定敘述
x, y = 1, 2
print("x = ",x, "y = ", y)

x =  1 y =  2


In [ ]:
x = 10  #integer
print(type(x))
y = 3.14  #float
print(type(y))
a = True  #booleans false
print(type(a))
b = "monkey"
print(type(b))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>


numpy:array
scipy:統計、資料處理
pandas:dataframe
matplotlib:繪圖
sympy,sckit-image

In [ ]:
import numpy as np
from numpy import random
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

# 可省略掉plt.show()
%matplotlib inline
# 小數點位數2位
%precision 2


'%.2f'

In [ ]:
data1 = np.array([9,3,4,0,6,7,8,1,5])
data1

array([9, 3, 4, 0, 6, 7, 8, 1, 5])

In [ ]:
#int64:有正負號的64位元整數
data1.dtype

dtype('int64')

In [ ]:
print("維度: ", data1.ndim)
print("元素: ", data1.size)

維度:  1
元素:  9


In [ ]:
data2 = data1 * 2

In [ ]:
data3 = data1 * data2
data3

array([162,  18,  32,   0,  72,  98, 128,   2,  50])

In [ ]:
data4 = data3 / data1
data4

<ipython-input-28-c4046be5b033>:1: RuntimeWarning: invalid value encountered in divide
  data4 = data3 / data1


array([18.,  6.,  8., nan, 12., 14., 16.,  2., 10.])

In [ ]:
print(data4.min())
print(data4.max())
print(data4.sum())
print(data4.cumsum())# 累加

nan
nan
nan
[18. 24. 32. nan nan nan nan nan nan]
